function props_table = Proportions_Of_CellTypes(all_data,cell_types)
% Plots a bar graph of the proportions of cell types in each group.
%
% INPUTS
% - all_data: struct generated by Shashwat's script
%       "a2_post_sorted_data_structure.m"
% - cell_types: cell array of cell types in order. Stored in the project
%       folder alongside all_data.mat.

groupNames = fieldnames(all_data);
colors = brewermap(length(cell_types),'Set2');

props_matrix = []; % should be [groups x cell types]

for groupNum = 1:length(groupNames)
    groupName = groupNames{groupNum};
    mouseNames = fieldnames(all_data.(groupName));

    groupCellCounts = zeros(1,length(cell_types)); % vector indexed by cell type
    total_n_cells = 0;

    for mouseNum = 1:length(mouseNames)
        mouseName = mouseNames{mouseNum};
        cellIDs = fieldnames(all_data.(groupName).(mouseName));

        for cellID_num = 1:length(cellIDs)
            cellID = cellIDs{cellID_num};
            isSingleUnit = all_data.(groupName).(mouseName).(cellID).IsSingleUnit;

            if isSingleUnit
                cellType = all_data.(groupName).(mouseName).(cellID).Cell_Type;
                cellTypeInd = find(strcmp(cell_types,cellType));
    
                groupCellCounts(cellTypeInd) = groupCellCounts(cellTypeInd) + 1;
                total_n_cells = total_n_cells + 1;
            end
        end
    end

    groupProps = (groupCellCounts / total_n_cells) * 100;

    props_matrix(groupNum,:) = groupProps;

end

figure;
b = bar(props_matrix, 'stacked');
for ii = 1:size(props_matrix,2)
    b(ii).FaceColor = colors(ii,:);
end

legend(cell_types{1:4}, 'Location','northeastoutside');
ylabel('Proportion of Cell Type (%)');
set(gca,'XTickLabel',groupNames);

ax = gca;
ax.XGrid = 'off';
ax.YGrid = 'on';

%% Plotting with Gramm
% props_table = array2table(props_matrix, 'VariableNames',cell_types);
% props_table = addvars(props_table, groupNames, 'Before',1, 'NewVariableNames','Group');
% props_table = stack(props_table, cell_types, 'NewDataVariableName','Proportion', 'IndexVariableName','Cell Type');
% 
% figure();
% g = gramm('x',props_table.Group, 'y',props_table.Proportion, 'color',props_table.('Cell Type'));
% g.geom_bar('stacked',1);
% 
% %g.set_color_options("map","lch");
% g.set_title('Proportions of Cell Types');
% g.set_names('x','', 'y','Proportion (%)', 'color','');
% g.set_order_options('color',0);

% g.draw();

end