function props_vec = Proportions_Of_CellTypes_v2(all_data,cell_types)
% Plots a bar graph of the proportions of cell types in each group.
%
% INPUTS
% - all_data: struct generated by Shashwat's script
%       "a2_post_sorted_data_structure.m"
% - cell_types: cell array of cell types in order. Stored in the project
%       folder alongside all_data.mat.

groupNames = fieldnames(all_data);
colors = jet(length(cell_types));

cellCounts_vec = [];


for groupNum = 1:length(groupNames)
    groupName = groupNames{groupNum};
    mouseNames = fieldnames(all_data.(groupName));

    for mouseNum = 1:length(mouseNames)
        mouseName = mouseNames{mouseNum};
        cellIDs = fieldnames(all_data.(groupName).(mouseName));

        for cellID_num = 1:length(cellIDs)
            cellID = cellIDs{cellID_num};
            cellType = all_data.(groupName).(mouseName).(cellID).Cell_Type;
            cellTypeInd = find(strcmp(cell_types,cellType));

            groupCellCounts(cellTypeInd) = groupCellCounts(cellTypeInd) + 1;
        end
    end


end

figure;
b = bar(props_vec, 'stacked');
for ii = 1:size(props_vec,2)
    b(ii).FaceColor = colors(ii,:);
end

legend(cell_types, 'Location','northeastoutside');
ylabel('Proportion of Cell Type (%)');
set(gca,'XTickLabel',groupNames);

ax = gca;
ax.XGrid = 'off';
ax.YGrid = 'on';

end