function electrode_data_original = mea_h5_to_mat_fun(h5_file_directory)

%{
    This file is for getting a MEA .h5 to an int32 matrix of [nElectrodess x nSamples] and saving it as a .mat for
    further analysis.
%}

%% Read and save data

%{
    This function reads the data from the directory as a struct data type and returns the actual data back. For this
    script to work, the MCS Matlab Datatools package needs to be added to the MATLAB path.
    Github: https://github.com/multichannelsystems/McsMatlabDataTools
%}

% Loading data generated by the Multi Channel DataManager with 'raw' as the dataType input which means there is
% no conversion done, the data is kept in ADC units.  
                
cfg = [];
cfg.dataType = 'raw';

h5_struct = McsHDF5.McsData(h5_file_directory, cfg);

% Return the data from within the "h5_struct" data structure
electrode_data_original = h5_struct.Recording{1}.AnalogStream{1}.ChannelData;

end

