function FiringRateByCellType(all_data,cell_types,cell_types_to_plot)
% Plots a box chart for each cell type where x is group, y is firing rate.
%
% INPUTS
% - all_data: struct generated by Shashwat's script
%       "a2_post_sorted_data_structure.m"
% - cell_types: cell array of cell types in order. Stored in the project
%       folder alongside all_data.mat.
% - cell_types_to_plot (optional): cell array of cell types you want to 
%   plot, in the order you want them plotted (left to right). If empty, all
%   cell types in cell_types will be plotted.

if nargin < 3
    cell_types_to_plot = cell_types;
end

groupNames = fieldnames(all_data);
colors = brewermap(length(cell_types),'Set2');

FR_vec = []; % vector of all firing rates
CellTypeInds_vec = []; % vector of all cell types corresponding to FRs
GroupInds_vec = []; % group number corresponding to each FR observation

for groupNum = 1:length(groupNames)
    groupName = groupNames{groupNum};
    mouseNames = fieldnames(all_data.(groupName));

%     nexttile(T);

    for mouseNum = 1:length(mouseNames)
        mouseName = mouseNames{mouseNum};
        cellIDs = fieldnames(all_data.(groupName).(mouseName));

        for cellID_num = 1:length(cellIDs)
            cellID = cellIDs{cellID_num};
            cellType = all_data.(groupName).(mouseName).(cellID).Cell_Type;
            if any(strcmp(cell_types_to_plot,cellType))
                cellTypeInd = find(strcmp(cell_types,cellType));
                firingRate = all_data.(groupName).(mouseName).(cellID).MeanFR_stim;
            
                FR_vec = [FR_vec; firingRate];
                CellTypeInds_vec = [CellTypeInds_vec; cellTypeInd];
                GroupInds_vec = [GroupInds_vec; groupNum];
            end
        end
    end
end

%% Plotting
figure();
T = tiledlayout(1,length(cell_types_to_plot));

for cellTypeInd = 1:length(cell_types)
    if any(strcmp(cell_types_to_plot,cell_types{cellTypeInd}))
        nexttile(T);
        xgroupdata = GroupInds_vec(find(CellTypeInds_vec==cellTypeInd));
        xgroupdata_categorical = categorical(xgroupdata,1:length(groupNames),groupNames);
        ydata = FR_vec(find(CellTypeInds_vec==cellTypeInd));

        boxchart(xgroupdata_categorical, ydata, "BoxFaceColor",colors(cellTypeInd,:), "MarkerColor",colors(cellTypeInd,:));
    
        title(cell_types{cellTypeInd});
        ax=gca; ax.XAxis.TickLength = [0 0];
    end
end

ylabel(T, 'Firing Rate (spikes/second)', 'fontsize',11);

end

